In [1]:
# Can add more features if we so desire; maybe GA1--GR1??  'AW1', 'AW2','AW3','AW4','AX1','AX2','AX3','AX4','AX5','AX6',
import sys
import os 
import pandas as pd
import numpy as np
sys.path.insert(0,'Data/Data Scripts')
import merge
merge.combined_data()

selected_columns = [
                    'STATION',
                    'LATITUDE',
                    'LONGITUDE',
                    'DATE',
                    'SOURCE',
                    'WND',
                    'TMP',
                    'CIG',
                    'VIS',
                    'DEW',
                    'SLP'
                    ]

FileNotFoundError: [Errno 2] No such file or directory: '../OK City Station Data/Raw Data'

In [110]:
df = df[selected_columns]




# some columns have different na codes; in columns with tuples there is often a entry 
# that indicates missing data, we should check these out.


# after dealing with na vals: some columns have tuples, we might want to explode 
# those columns into separate columns too

In [111]:
df

,STATION,LATITUDE,LONGITUDE,DATE,SOURCE,WND,TMP,CIG,VIS,DEW,SLP
0,72353013967,35.3889,-97.6006,2004-05-08T18:00:00,3,"180,5,N,0093,5","+0278,5","22000,5,M,N","016000,5,N,1","+0178,5","10159,5"
1,72353013967,35.3889,-97.6006,2004-05-08T18:52:00,C,"180,5,N,0077,5","+0283,5","22000,5,M,N","016000,5,N,1","+0178,5","10152,5"
2,72353013967,35.3889,-97.6006,2004-05-08T19:00:00,9,"999,9,9,9999,9","+9999,9","99999,9,9,9","999999,9,9,9","+9999,9","99999,9"
3,72353013967,35.3889,-97.6006,2004-05-08T19:52:00,C,"170,5,N,0082,5","+0289,5","22000,5,M,N","016000,5,N,1","+0178,5","10149,5"
4,72353013967,35.3889,-97.6006,2004-05-08T20:00:00,9,"999,9,9,9999,9","+9999,9","99999,9,9,9","999999,9,9,9","+9999,9","99999,9"
...,...,...,...,...,...,...,...,...,...,...,...
1370630,72357099999,35.2330,-97.4500,2005-12-31T22:32:00,4,"150,1,N,0036,1","+0170,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9"
1370631,72357099999,35.2330,-97.4500,2005-12-31T22:52:00,4,"150,1,N,0031,1","+0160,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9"
1370632,72357099999,35.2330,-97.4500,2005-12-31T23:12:00,4,"160,1,N,0026,1","+0160,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9"
1370633,72357099999,35.2330,-97.4500,2005-12-31T23:32:00,4,"130,1,N,0021,1","+0150,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9"
1370634,72357099999,35.2330,-97.4500,2005-12-31T23:52:00,4,"130,1,N,0015,1","+0140,1","22000,1,9,N","016093,1,N,1","-0030,1","99999,9"

In [112]:
s = df['DATE'].apply(lambda r : type(r))
s.unique()
# data types here are strings as predicted

array([<class 'str'>], dtype=object)

In [113]:

# Split 'DATE' feature into two new features 'YEAR-MONTH-DAY' and 'TIME'
# First make sure these are not already features
assert ('TIME' not in df.columns) 
assert ('YEAR-MONTH-DAY' not in df.columns)
new_df=df.copy()
new_df['YEAR-MONTH-DAY'] = df['DATE'].apply(lambda r: r.split('T')[0])
new_df['TIME'] = df['DATE'].apply(lambda r: r.split('T')[1])

In [114]:
new_df.drop(['DATE'],axis=1,inplace=True)

In [115]:
new_df

,STATION,LATITUDE,LONGITUDE,SOURCE,WND,TMP,CIG,VIS,DEW,SLP,YEAR-MONTH-DAY,TIME
0,72353013967,35.3889,-97.6006,3,"180,5,N,0093,5","+0278,5","22000,5,M,N","016000,5,N,1","+0178,5","10159,5",2004-05-08,18:00:00
1,72353013967,35.3889,-97.6006,C,"180,5,N,0077,5","+0283,5","22000,5,M,N","016000,5,N,1","+0178,5","10152,5",2004-05-08,18:52:00
2,72353013967,35.3889,-97.6006,9,"999,9,9,9999,9","+9999,9","99999,9,9,9","999999,9,9,9","+9999,9","99999,9",2004-05-08,19:00:00
3,72353013967,35.3889,-97.6006,C,"170,5,N,0082,5","+0289,5","22000,5,M,N","016000,5,N,1","+0178,5","10149,5",2004-05-08,19:52:00
4,72353013967,35.3889,-97.6006,9,"999,9,9,9999,9","+9999,9","99999,9,9,9","999999,9,9,9","+9999,9","99999,9",2004-05-08,20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1370630,72357099999,35.2330,-97.4500,4,"150,1,N,0036,1","+0170,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9",2005-12-31,22:32:00
1370631,72357099999,35.2330,-97.4500,4,"150,1,N,0031,1","+0160,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9",2005-12-31,22:52:00
1370632,72357099999,35.2330,-97.4500,4,"160,1,N,0026,1","+0160,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9",2005-12-31,23:12:00
1370633,72357099999,35.2330,-97.4500,4,"130,1,N,0021,1","+0150,1","22000,1,9,N","016093,1,N,1","-0020,1","99999,9",2005-12-31,23:32:00
1370634,72357099999,35.2330,-97.4500,4,"130,1,N,0015,1","+0140,1","22000,1,9,N","016093,1,N,1","-0030,1","99999,9",2005-12-31,23:52:00

In [117]:
# combined oklahoma tornadoes

path = 'Data/Storm Event Data/Cleaned Data/oklahoma_tornadoes_2000_2021.csv'
df2 = pd.read_csv(path).copy()
# Really will only care about 'BEGIN_DATE_TIME', 'END_DATE_TIME', 'BEGIN_LAT',
# 'END_LAT', 'BEGIN_LON', 'END_LON'

df2 = df2[
        [
        'BEGIN_DATE_TIME', 
        'END_DATE_TIME', 
        'BEGIN_LAT', 
        'END_LAT', 
        'BEGIN_LON', 
        'END_LON'
        ]
        ]

In [118]:
# split BEGIN-DATE-TIME and END-DATE-TIME into new columns 
# BEGIN-DATE and BEGIN-TIME
# END-DATE and END-TIME respectively

# already has BEGIN_TIME and END_TIME, but we will replace these since they are not
# in the correct format
df2['BEGIN_DATE_TIME']

0     10-APR-05 19:30:00
1     31-MAR-08 00:23:00
2     31-MAR-08 00:39:00
3     07-MAY-08 16:22:00
4     07-MAY-08 16:02:00
5     01-MAY-08 18:29:00
6     07-MAY-07 01:32:00
7     22-OCT-00 18:14:00
8     22-OCT-00 18:02:00
9     10-FEB-09 14:53:00
10    10-FEB-09 14:36:00
11    15-APR-03 22:41:00
12    09-MAY-03 22:06:00
13    08-MAY-03 16:15:00
14    09-MAY-03 21:10:00
15    09-MAY-03 21:29:00
16    09-MAY-03 21:18:00
17    29-MAY-04 20:04:00
18    10-NOV-04 16:36:00
19    10-NOV-04 16:43:00
20    10-NOV-04 17:00:00
21    26-APR-16 19:49:00
22    26-APR-16 19:11:00
23    26-APR-16 19:43:00
24    09-OCT-18 07:24:00
25    09-OCT-18 07:42:00
26    09-OCT-18 07:33:00
27    09-OCT-18 07:28:00
28    25-MAR-15 17:29:00
29    06-MAY-15 19:41:00
30    14-DEC-14 17:09:00
31    31-MAY-13 18:53:00
32    31-MAY-13 17:54:00
33    19-MAY-13 15:22:00
34    19-MAY-13 15:33:00
35    19-MAY-13 15:41:00
36    31-MAY-13 18:35:00
37    25-MAY-19 21:53:00
38    25-MAY-19 21:57:00
39    26-AUG-19 20:01:00
40    25-MAY-19 21:46:00
41    25-MAY-19 21:49:00
42    10-OCT-21 19:21:00
43    13-OCT-21 04:15:00
44    13-OCT-21 04:22:00
45    10-MAY-10 16:35:00
46    10-MAY-10 16:13:00
Name: BEGIN_DATE_TIME, dtype: object

In [119]:
df2['BEGIN_DATE_TIME'].apply(lambda r: r.split(' '))

0     [10-APR-05, 19:30:00]
1     [31-MAR-08, 00:23:00]
2     [31-MAR-08, 00:39:00]
3     [07-MAY-08, 16:22:00]
4     [07-MAY-08, 16:02:00]
5     [01-MAY-08, 18:29:00]
6     [07-MAY-07, 01:32:00]
7     [22-OCT-00, 18:14:00]
8     [22-OCT-00, 18:02:00]
9     [10-FEB-09, 14:53:00]
10    [10-FEB-09, 14:36:00]
11    [15-APR-03, 22:41:00]
12    [09-MAY-03, 22:06:00]
13    [08-MAY-03, 16:15:00]
14    [09-MAY-03, 21:10:00]
15    [09-MAY-03, 21:29:00]
16    [09-MAY-03, 21:18:00]
17    [29-MAY-04, 20:04:00]
18    [10-NOV-04, 16:36:00]
19    [10-NOV-04, 16:43:00]
20    [10-NOV-04, 17:00:00]
21    [26-APR-16, 19:49:00]
22    [26-APR-16, 19:11:00]
23    [26-APR-16, 19:43:00]
24    [09-OCT-18, 07:24:00]
25    [09-OCT-18, 07:42:00]
26    [09-OCT-18, 07:33:00]
27    [09-OCT-18, 07:28:00]
28    [25-MAR-15, 17:29:00]
29    [06-MAY-15, 19:41:00]
30    [14-DEC-14, 17:09:00]
31    [31-MAY-13, 18:53:00]
32    [31-MAY-13, 17:54:00]
33    [19-MAY-13, 15:22:00]
34    [19-MAY-13, 15:33:00]
35    [19-MAY-13, 15:41:00]
36    [31-MAY-13, 18:35:00]
37    [25-MAY-19, 21:53:00]
38    [25-MAY-19, 21:57:00]
39    [26-AUG-19, 20:01:00]
40    [25-MAY-19, 21:46:00]
41    [25-MAY-19, 21:49:00]
42    [10-OCT-21, 19:21:00]
43    [13-OCT-21, 04:15:00]
44    [13-OCT-21, 04:22:00]
45    [10-MAY-10, 16:35:00]
46    [10-MAY-10, 16:13:00]
Name: BEGIN_DATE_TIME, dtype: object

In [120]:
df2['END_DATE_TIME']

0     10-APR-05 19:44:00
1     31-MAR-08 00:23:00
2     31-MAR-08 00:45:00
3     07-MAY-08 16:26:00
4     07-MAY-08 16:09:00
5     01-MAY-08 18:29:00
6     07-MAY-07 01:33:00
7     22-OCT-00 18:22:00
8     22-OCT-00 18:07:00
9     10-FEB-09 15:03:00
10    10-FEB-09 14:37:00
11    15-APR-03 22:45:00
12    09-MAY-03 22:15:00
13    08-MAY-03 16:38:00
14    09-MAY-03 21:14:00
15    09-MAY-03 22:06:00
16    09-MAY-03 21:18:00
17    29-MAY-04 20:10:00
18    10-NOV-04 16:38:00
19    10-NOV-04 16:50:00
20    10-NOV-04 17:03:00
21    26-APR-16 19:50:00
22    26-APR-16 19:12:00
23    26-APR-16 19:53:00
24    09-OCT-18 07:25:00
25    09-OCT-18 07:48:00
26    09-OCT-18 07:42:00
27    09-OCT-18 07:46:00
28    25-MAR-15 17:29:00
29    06-MAY-15 19:48:00
30    14-DEC-14 17:10:00
31    31-MAY-13 18:55:00
32    31-MAY-13 18:09:00
33    19-MAY-13 15:30:00
34    19-MAY-13 15:34:00
35    19-MAY-13 15:54:00
36    31-MAY-13 18:37:00
37    25-MAY-19 21:53:00
38    25-MAY-19 21:57:00
39    26-AUG-19 20:01:00
40    25-MAY-19 21:47:00
41    25-MAY-19 21:50:00
42    10-OCT-21 19:25:00
43    13-OCT-21 04:19:00
44    13-OCT-21 04:28:00
45    10-MAY-10 16:51:00
46    10-MAY-10 16:13:00
Name: END_DATE_TIME, dtype: object

In [121]:
# columns BEGIN-DATE and BEGIN-TIME
new_df2 = df2.copy()
new_df2['BEGIN_DATE'] = df2['BEGIN_DATE_TIME'].apply(lambda r : r.split(' ')[0])
new_df2['BEGIN_TIME'] = df2['BEGIN_DATE_TIME'].apply(lambda r : r.split(' ')[1])
new_df2['END_DATE'] = df2['END_DATE_TIME'].apply(lambda r : r.split(' ')[0])
new_df2['END_TIME'] = df2['END_DATE_TIME'].apply(lambda r : r.split(' ')[1])

In [122]:
new_df2['BEGIN_DATE']

0     10-APR-05
1     31-MAR-08
2     31-MAR-08
3     07-MAY-08
4     07-MAY-08
5     01-MAY-08
6     07-MAY-07
7     22-OCT-00
8     22-OCT-00
9     10-FEB-09
10    10-FEB-09
11    15-APR-03
12    09-MAY-03
13    08-MAY-03
14    09-MAY-03
15    09-MAY-03
16    09-MAY-03
17    29-MAY-04
18    10-NOV-04
19    10-NOV-04
20    10-NOV-04
21    26-APR-16
22    26-APR-16
23    26-APR-16
24    09-OCT-18
25    09-OCT-18
26    09-OCT-18
27    09-OCT-18
28    25-MAR-15
29    06-MAY-15
30    14-DEC-14
31    31-MAY-13
32    31-MAY-13
33    19-MAY-13
34    19-MAY-13
35    19-MAY-13
36    31-MAY-13
37    25-MAY-19
38    25-MAY-19
39    26-AUG-19
40    25-MAY-19
41    25-MAY-19
42    10-OCT-21
43    13-OCT-21
44    13-OCT-21
45    10-MAY-10
46    10-MAY-10
Name: BEGIN_DATE, dtype: object

In [123]:
new_df2['BEGIN_TIME']

0     19:30:00
1     00:23:00
2     00:39:00
3     16:22:00
4     16:02:00
5     18:29:00
6     01:32:00
7     18:14:00
8     18:02:00
9     14:53:00
10    14:36:00
11    22:41:00
12    22:06:00
13    16:15:00
14    21:10:00
15    21:29:00
16    21:18:00
17    20:04:00
18    16:36:00
19    16:43:00
20    17:00:00
21    19:49:00
22    19:11:00
23    19:43:00
24    07:24:00
25    07:42:00
26    07:33:00
27    07:28:00
28    17:29:00
29    19:41:00
30    17:09:00
31    18:53:00
32    17:54:00
33    15:22:00
34    15:33:00
35    15:41:00
36    18:35:00
37    21:53:00
38    21:57:00
39    20:01:00
40    21:46:00
41    21:49:00
42    19:21:00
43    04:15:00
44    04:22:00
45    16:35:00
46    16:13:00
Name: BEGIN_TIME, dtype: object

In [124]:
new_df2.drop(['BEGIN_DATE_TIME','END_DATE_TIME'],axis=1,inplace=True)

In [125]:
new_df2

,BEGIN_LAT,END_LAT,BEGIN_LON,END_LON,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME
0,35.38333,35.45000,-97.23333,-97.21667,10-APR-05,19:30:00,10-APR-05,19:44:00
1,35.65000,35.65000,-97.64030,-97.64030,31-MAR-08,00:23:00,31-MAR-08,00:23:00
2,35.65000,35.68340,-97.55120,-97.49700,31-MAR-08,00:39:00,31-MAR-08,00:45:00
3,35.63690,35.61010,-97.58410,-97.52960,07-MAY-08,16:22:00,07-MAY-08,16:26:00
4,35.51830,35.52550,-97.66460,-97.60360,07-MAY-08,16:02:00,07-MAY-08,16:09:00
5,35.50020,35.50020,-97.28260,-97.28260,01-MAY-08,18:29:00,01-MAY-08,18:29:00
6,35.50930,35.52190,-97.47760,-97.46110,07-MAY-07,01:32:00,07-MAY-07,01:33:00
7,35.43333,35.48333,-97.50000,-97.51667,22-OCT-00,18:14:00,22-OCT-00,18:22:00
8,35.38333,35.40000,-97.53333,-97.50000,22-OCT-00,18:02:00,22-OCT-00,18:07:00
9,35.66310,35.72540,-97.53090,-97.48230,10-FEB-09,14:53:00,10-FEB-09,15:03:00
10,35.55530,35.56020,-97.63970,-97.62960,10-FEB-09,14:36:00,10-FEB-09,14:37:00
11,35.83333,35.83333,-99.53333,-99.53333,15-APR-03,22:41:00,15-APR-03,22:45:00
12,36.70000,36.70000,-97.08333,-97.08333,09-MAY-03,22:06:00,09-MAY-03,22:15:00
13,35.40000,35.46667,-97.48333,-97.25000,08-MAY-03,16:15:00,08-MAY-03,16:38:00
14,35.38333,35.38333,-98.63333,-98.63333,09-MAY-03,21:10:00,09-MAY-03,21:14:00
15,36.90000,36.90000,-97.06667,-97.06667,09-MAY-03,21:29:00,09-MAY-03,22:06:00
16,35.70000,35.70000,-98.38333,-98.38333,09-MAY-03,21:18:00,09-MAY-03,21:18:00
17,35.68333,35.68333,-97.20000,-97.20000,29-MAY-04,20:04:00,29-MAY-04,20:10:00
18,35.50000,35.51667,-97.35000,-97.33333,10-NOV-04,16:36:00,10-NOV-04,16:38:00
19,35.53333,35.56667,-97.30000,-97.23333,10-NOV-04,16:43:00,10-NOV-04,16:50:00
20,35.61667,35.63333,-97.20000,-97.18333,10-NOV-04,17:00:00,10-NOV-04,17:03:00
21,35.71000,35.72500,-97.33000,-97.31000,26-APR-16,19:49:00,26-APR-16,19:50:00
22,35.43200,35.43900,-97.67200,-97.66300,26-APR-16,19:11:00,26-APR-16,19:12:00
23,35.60600,35.70100,-97.33600,-97.21900,26-APR-16,19:43:00,26-APR-16,19:53:00
24,35.49300,35.50600,-97.49100,-97.48400,09-OCT-18,07:24:00,09-OCT-18,07:25:00
25,35.49100,35.53700,-97.26400,-97.21000,09-OCT-18,07:42:00,09-OCT-18,07:48:00
26,35.59200,35.66500,-97.43600,-97.38300,09-OCT-18,07:33:00,09-OCT-18,07:42:00
27,35.43300,35.55200,-97.40400,-97.29800,09-OCT-18,07:28:00,09-OCT-18,07:46:00
28,35.47600,35.47600,-97.63500,-97.63500,25-MAR-15,17:29:00,25-MAR-15,17:29:00
29,35.40610,35.42090,-97.47690,-97.49940,06-MAY-15,19:41:00,06-MAY-15,19:48:00
30,35.62000,35.62170,-97.38000,-97.37780,14-DEC-14,17:09:00,14-DEC-14,17:10:00
31,35.40600,35.40400,-97.55100,-97.53100,31-MAY-13,18:53:00,31-MAY-13,18:55:00
32,35.44900,35.44800,-97.67100,-97.59900,31-MAY-13,17:54:00,31-MAY-13,18:09:00
33,35.62400,35.64300,-97.48100,-97.40600,19-MAY-13,15:22:00,19-MAY-13,15:30:00
34,35.65340,35.65440,-97.36210,-97.35230,19-MAY-13,15:33:00,19-MAY-13,15:34:00
35,35.69300,35.72400,-97.23200,-97.15400,19-MAY-13,15:41:00,19-MAY-13,15:54:00
36,35.41100,35.41000,-97.45700,-97.44900,31-MAY-13,18:35:00,31-MAY-13,18:37:00
37,35.51600,35.51600,-97.49200,-97.49200,25-MAY-19,21:53:00,25-MAY-19,21:53:00
38,35.53640,35.53640,-97.45950,-97.45950,25-MAY-19,21:57:00,25-MAY-19,21:57:00
39,35.72600,35.72600,-97.51400,-97.51400,26-AUG-19,20:01:00,26-AUG-19,20:01:00
40,35.48100,35.48200,-97.59900,-97.58300,25-MAY-19,21:46:00,25-MAY-19,21:47:00
41,35.49000,35.49400,-97.53900,-97.53000,25-MAY-19,21:49:00,25-MAY-19,21:50:00
42,35.53500,35.56500,-97.17900,-97.14100,10-OCT-21,19:21:00,10-OCT-21,19:25:00
43,35.47500,35.49200,-97.56200,-97.51000,13-OCT-21,04:15:00,13-OCT-21,04:19:00
44,35.50800,35.53700,-97.45950,-97.39300,13-OCT-21,04:22:00,13-OCT-21,04:28:00
45,35.37700,35.47000,-97.30500,-97.15500,10-MAY-10,16:35:00,10-MAY-10,16:51:00
46,35.60400,35.60400,-97.54300,-97.54300,10-MAY-10,16:13:00,10-MAY-10,16:13:00

In [126]:
# Change format of 'BEGIN_DATE' and 'END_DATE' to match that of 'YEAR_MONTH_DAY' in station data

month_num = {
            'JAN':'01',
            'FEB':'02',
            'MAR':'03', 
            'APR':'04', 
            'MAY':'05', 
            'JUN':'06', 
            'JUL':'07', 
            'AUG':'08', 
            'SEP':'09', 
            'OCT':'10', 
            'NOV':'11', 
            'DEC':'12'
            }

new_df2['BEGIN_DATE'] = new_df2['BEGIN_DATE'].apply(lambda r: f'{r.split('-')[0]}-{month_num[r.split('-')[1]]}-{r.split('-')[2]}')
new_df2['END_DATE'] = new_df2['END_DATE'].apply(lambda r: f'{r.split('-')[0]}-{month_num[r.split('-')[1]]}-{r.split('-')[2]}')

In [127]:
new_df2

,BEGIN_LAT,END_LAT,BEGIN_LON,END_LON,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME
0,35.38333,35.45000,-97.23333,-97.21667,10-04-05,19:30:00,10-04-05,19:44:00
1,35.65000,35.65000,-97.64030,-97.64030,31-03-08,00:23:00,31-03-08,00:23:00
2,35.65000,35.68340,-97.55120,-97.49700,31-03-08,00:39:00,31-03-08,00:45:00
3,35.63690,35.61010,-97.58410,-97.52960,07-05-08,16:22:00,07-05-08,16:26:00
4,35.51830,35.52550,-97.66460,-97.60360,07-05-08,16:02:00,07-05-08,16:09:00
5,35.50020,35.50020,-97.28260,-97.28260,01-05-08,18:29:00,01-05-08,18:29:00
6,35.50930,35.52190,-97.47760,-97.46110,07-05-07,01:32:00,07-05-07,01:33:00
7,35.43333,35.48333,-97.50000,-97.51667,22-10-00,18:14:00,22-10-00,18:22:00
8,35.38333,35.40000,-97.53333,-97.50000,22-10-00,18:02:00,22-10-00,18:07:00
9,35.66310,35.72540,-97.53090,-97.48230,10-02-09,14:53:00,10-02-09,15:03:00
10,35.55530,35.56020,-97.63970,-97.62960,10-02-09,14:36:00,10-02-09,14:37:00
11,35.83333,35.83333,-99.53333,-99.53333,15-04-03,22:41:00,15-04-03,22:45:00
12,36.70000,36.70000,-97.08333,-97.08333,09-05-03,22:06:00,09-05-03,22:15:00
13,35.40000,35.46667,-97.48333,-97.25000,08-05-03,16:15:00,08-05-03,16:38:00
14,35.38333,35.38333,-98.63333,-98.63333,09-05-03,21:10:00,09-05-03,21:14:00
15,36.90000,36.90000,-97.06667,-97.06667,09-05-03,21:29:00,09-05-03,22:06:00
16,35.70000,35.70000,-98.38333,-98.38333,09-05-03,21:18:00,09-05-03,21:18:00
17,35.68333,35.68333,-97.20000,-97.20000,29-05-04,20:04:00,29-05-04,20:10:00
18,35.50000,35.51667,-97.35000,-97.33333,10-11-04,16:36:00,10-11-04,16:38:00
19,35.53333,35.56667,-97.30000,-97.23333,10-11-04,16:43:00,10-11-04,16:50:00
20,35.61667,35.63333,-97.20000,-97.18333,10-11-04,17:00:00,10-11-04,17:03:00
21,35.71000,35.72500,-97.33000,-97.31000,26-04-16,19:49:00,26-04-16,19:50:00
22,35.43200,35.43900,-97.67200,-97.66300,26-04-16,19:11:00,26-04-16,19:12:00
23,35.60600,35.70100,-97.33600,-97.21900,26-04-16,19:43:00,26-04-16,19:53:00
24,35.49300,35.50600,-97.49100,-97.48400,09-10-18,07:24:00,09-10-18,07:25:00
25,35.49100,35.53700,-97.26400,-97.21000,09-10-18,07:42:00,09-10-18,07:48:00
26,35.59200,35.66500,-97.43600,-97.38300,09-10-18,07:33:00,09-10-18,07:42:00
27,35.43300,35.55200,-97.40400,-97.29800,09-10-18,07:28:00,09-10-18,07:46:00
28,35.47600,35.47600,-97.63500,-97.63500,25-03-15,17:29:00,25-03-15,17:29:00
29,35.40610,35.42090,-97.47690,-97.49940,06-05-15,19:41:00,06-05-15,19:48:00
30,35.62000,35.62170,-97.38000,-97.37780,14-12-14,17:09:00,14-12-14,17:10:00
31,35.40600,35.40400,-97.55100,-97.53100,31-05-13,18:53:00,31-05-13,18:55:00
32,35.44900,35.44800,-97.67100,-97.59900,31-05-13,17:54:00,31-05-13,18:09:00
33,35.62400,35.64300,-97.48100,-97.40600,19-05-13,15:22:00,19-05-13,15:30:00
34,35.65340,35.65440,-97.36210,-97.35230,19-05-13,15:33:00,19-05-13,15:34:00
35,35.69300,35.72400,-97.23200,-97.15400,19-05-13,15:41:00,19-05-13,15:54:00
36,35.41100,35.41000,-97.45700,-97.44900,31-05-13,18:35:00,31-05-13,18:37:00
37,35.51600,35.51600,-97.49200,-97.49200,25-05-19,21:53:00,25-05-19,21:53:00
38,35.53640,35.53640,-97.45950,-97.45950,25-05-19,21:57:00,25-05-19,21:57:00
39,35.72600,35.72600,-97.51400,-97.51400,26-08-19,20:01:00,26-08-19,20:01:00
40,35.48100,35.48200,-97.59900,-97.58300,25-05-19,21:46:00,25-05-19,21:47:00
41,35.49000,35.49400,-97.53900,-97.53000,25-05-19,21:49:00,25-05-19,21:50:00
42,35.53500,35.56500,-97.17900,-97.14100,10-10-21,19:21:00,10-10-21,19:25:00
43,35.47500,35.49200,-97.56200,-97.51000,13-10-21,04:15:00,13-10-21,04:19:00
44,35.50800,35.53700,-97.45950,-97.39300,13-10-21,04:22:00,13-10-21,04:28:00
45,35.37700,35.47000,-97.30500,-97.15500,10-05-10,16:35:00,10-05-10,16:51:00
46,35.60400,35.60400,-97.54300,-97.54300,10-05-10,16:13:00,10-05-10,16:13:00

In [128]:
new_df2['BEGIN_DATE']=new_df2['BEGIN_DATE'].apply(lambda r: f'20{r.split('-')[2]}-{r.split('-')[1]}-{r.split('-')[0]}')
new_df2['END_DATE']=new_df2['END_DATE'].apply(lambda r: f'20{r.split('-')[2]}-{r.split('-')[1]}-{r.split('-')[0]}')

In [129]:
new_df2

,BEGIN_LAT,END_LAT,BEGIN_LON,END_LON,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME
0,35.38333,35.45000,-97.23333,-97.21667,2005-04-10,19:30:00,2005-04-10,19:44:00
1,35.65000,35.65000,-97.64030,-97.64030,2008-03-31,00:23:00,2008-03-31,00:23:00
2,35.65000,35.68340,-97.55120,-97.49700,2008-03-31,00:39:00,2008-03-31,00:45:00
3,35.63690,35.61010,-97.58410,-97.52960,2008-05-07,16:22:00,2008-05-07,16:26:00
4,35.51830,35.52550,-97.66460,-97.60360,2008-05-07,16:02:00,2008-05-07,16:09:00
5,35.50020,35.50020,-97.28260,-97.28260,2008-05-01,18:29:00,2008-05-01,18:29:00
6,35.50930,35.52190,-97.47760,-97.46110,2007-05-07,01:32:00,2007-05-07,01:33:00
7,35.43333,35.48333,-97.50000,-97.51667,2000-10-22,18:14:00,2000-10-22,18:22:00
8,35.38333,35.40000,-97.53333,-97.50000,2000-10-22,18:02:00,2000-10-22,18:07:00
9,35.66310,35.72540,-97.53090,-97.48230,2009-02-10,14:53:00,2009-02-10,15:03:00
10,35.55530,35.56020,-97.63970,-97.62960,2009-02-10,14:36:00,2009-02-10,14:37:00
11,35.83333,35.83333,-99.53333,-99.53333,2003-04-15,22:41:00,2003-04-15,22:45:00
12,36.70000,36.70000,-97.08333,-97.08333,2003-05-09,22:06:00,2003-05-09,22:15:00
13,35.40000,35.46667,-97.48333,-97.25000,2003-05-08,16:15:00,2003-05-08,16:38:00
14,35.38333,35.38333,-98.63333,-98.63333,2003-05-09,21:10:00,2003-05-09,21:14:00
15,36.90000,36.90000,-97.06667,-97.06667,2003-05-09,21:29:00,2003-05-09,22:06:00
16,35.70000,35.70000,-98.38333,-98.38333,2003-05-09,21:18:00,2003-05-09,21:18:00
17,35.68333,35.68333,-97.20000,-97.20000,2004-05-29,20:04:00,2004-05-29,20:10:00
18,35.50000,35.51667,-97.35000,-97.33333,2004-11-10,16:36:00,2004-11-10,16:38:00
19,35.53333,35.56667,-97.30000,-97.23333,2004-11-10,16:43:00,2004-11-10,16:50:00
20,35.61667,35.63333,-97.20000,-97.18333,2004-11-10,17:00:00,2004-11-10,17:03:00
21,35.71000,35.72500,-97.33000,-97.31000,2016-04-26,19:49:00,2016-04-26,19:50:00
22,35.43200,35.43900,-97.67200,-97.66300,2016-04-26,19:11:00,2016-04-26,19:12:00
23,35.60600,35.70100,-97.33600,-97.21900,2016-04-26,19:43:00,2016-04-26,19:53:00
24,35.49300,35.50600,-97.49100,-97.48400,2018-10-09,07:24:00,2018-10-09,07:25:00
25,35.49100,35.53700,-97.26400,-97.21000,2018-10-09,07:42:00,2018-10-09,07:48:00
26,35.59200,35.66500,-97.43600,-97.38300,2018-10-09,07:33:00,2018-10-09,07:42:00
27,35.43300,35.55200,-97.40400,-97.29800,2018-10-09,07:28:00,2018-10-09,07:46:00
28,35.47600,35.47600,-97.63500,-97.63500,2015-03-25,17:29:00,2015-03-25,17:29:00
29,35.40610,35.42090,-97.47690,-97.49940,2015-05-06,19:41:00,2015-05-06,19:48:00
30,35.62000,35.62170,-97.38000,-97.37780,2014-12-14,17:09:00,2014-12-14,17:10:00
31,35.40600,35.40400,-97.55100,-97.53100,2013-05-31,18:53:00,2013-05-31,18:55:00
32,35.44900,35.44800,-97.67100,-97.59900,2013-05-31,17:54:00,2013-05-31,18:09:00
33,35.62400,35.64300,-97.48100,-97.40600,2013-05-19,15:22:00,2013-05-19,15:30:00
34,35.65340,35.65440,-97.36210,-97.35230,2013-05-19,15:33:00,2013-05-19,15:34:00
35,35.69300,35.72400,-97.23200,-97.15400,2013-05-19,15:41:00,2013-05-19,15:54:00
36,35.41100,35.41000,-97.45700,-97.44900,2013-05-31,18:35:00,2013-05-31,18:37:00
37,35.51600,35.51600,-97.49200,-97.49200,2019-05-25,21:53:00,2019-05-25,21:53:00
38,35.53640,35.53640,-97.45950,-97.45950,2019-05-25,21:57:00,2019-05-25,21:57:00
39,35.72600,35.72600,-97.51400,-97.51400,2019-08-26,20:01:00,2019-08-26,20:01:00
40,35.48100,35.48200,-97.59900,-97.58300,2019-05-25,21:46:00,2019-05-25,21:47:00
41,35.49000,35.49400,-97.53900,-97.53000,2019-05-25,21:49:00,2019-05-25,21:50:00
42,35.53500,35.56500,-97.17900,-97.14100,2021-10-10,19:21:00,2021-10-10,19:25:00
43,35.47500,35.49200,-97.56200,-97.51000,2021-10-13,04:15:00,2021-10-13,04:19:00
44,35.50800,35.53700,-97.45950,-97.39300,2021-10-13,04:22:00,2021-10-13,04:28:00
45,35.37700,35.47000,-97.30500,-97.15500,2010-05-10,16:35:00,2010-05-10,16:51:00
46,35.60400,35.60400,-97.54300,-97.54300,2010-05-10,16:13:00,2010-05-10,16:13:00

In [133]:
# desired radius 

final_df = pd.merge(left=new_df,right=new_df2,how ='outer',left_on='YEAR-MONTH-DAY',right_on='BEGIN_DATE')

In [134]:
final_df

,STATION,LATITUDE,LONGITUDE,SOURCE,WND,TMP,CIG,VIS,DEW,SLP,YEAR-MONTH-DAY,TIME,BEGIN_LAT,END_LAT,BEGIN_LON,END_LON,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME
0,72353013967,35.38890,-97.60060,3,"130,5,N,0026,5","+0106,5","22000,5,M,N","016000,5,N,1","+0022,5","10160,5",2000-01-01,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,72353013967,35.38890,-97.60060,3,"150,5,N,0026,5","+0094,5","22000,5,M,N","016000,5,N,1","+0017,5","10162,5",2000-01-01,01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,72353013967,35.38890,-97.60060,3,"140,5,N,0036,5","+0067,5","22000,5,M,N","016000,5,N,1","+0017,5","10160,5",2000-01-01,02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,72353013967,35.38890,-97.60060,3,"180,5,N,0021,5","+0050,5","22000,5,M,N","016000,5,N,1","+0011,5","10161,5",2000-01-01,03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,72353013967,35.38890,-97.60060,3,"150,5,N,0031,5","+0044,5","22000,5,M,N","016000,5,N,1","+0011,5","10159,5",2000-01-01,04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1375491,72354403954,35.54113,-97.64725,7,"210,5,N,0077,5","+0189,5","22000,5,9,N","016093,5,N,5","+0039,5","10027,5",2021-12-31,19:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1375492,72354403954,35.54113,-97.64725,7,"200,5,N,0093,5","+0183,5","22000,5,9,N","016093,5,N,5","+0050,5","10027,5",2021-12-31,20:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1375493,72354403954,35.54113,-97.64725,7,"190,5,N,0057,5","+0178,5","02896,5,M,N","016093,5,N,5","+0067,5","10024,5",2021-12-31,21:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1375494,72354403954,35.54113,-97.64725,7,"190,5,N,0046,5","+0172,5","03048,5,M,N","016093,5,N,5","+0072,5","10027,5",2021-12-31,22:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1375495,72354403954,35.54113,-97.64725,7,"190,5,N,0082,5","+0144,5","02438,5,M,N","016093,5,N,5","+0106,5","10039,5",2021-12-31,23:53:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
final_df[final_df['YEAR-MONTH-DAY']==final_df['BEGIN_DATE']]

,STATION,LATITUDE,LONGITUDE,SOURCE,WND,TMP,CIG,VIS,DEW,SLP,YEAR-MONTH-DAY,TIME,BEGIN_LAT,END_LAT,BEGIN_LON,END_LON,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME
38899,72353013967,35.38890,-97.60060,3,"120,5,N,0067,5","+0161,5","00274,5,M,N","004800,5,N,1","+0161,5","10138,5",2000-10-22,00:00:00,35.43333,35.48333,-97.50000,-97.51667,2000-10-22,18:14:00,2000-10-22,18:22:00
38900,72353013967,35.38890,-97.60060,3,"120,5,N,0067,5","+0161,5","00274,5,M,N","004800,5,N,1","+0161,5","10138,5",2000-10-22,00:00:00,35.38333,35.40000,-97.53333,-97.50000,2000-10-22,18:02:00,2000-10-22,18:07:00
38901,72353013967,35.38890,-97.60060,C,"110,5,N,0072,5","+0161,5","00183,5,M,N","004800,5,N,1","+0161,5","10140,5",2000-10-22,00:53:00,35.43333,35.48333,-97.50000,-97.51667,2000-10-22,18:14:00,2000-10-22,18:22:00
38902,72353013967,35.38890,-97.60060,C,"110,5,N,0072,5","+0161,5","00183,5,M,N","004800,5,N,1","+0161,5","10140,5",2000-10-22,00:53:00,35.38333,35.40000,-97.53333,-97.50000,2000-10-22,18:02:00,2000-10-22,18:07:00
38903,72353013967,35.38890,-97.60060,3,"110,1,N,0067,1","+0160,1","00120,1,9,N","004828,1,N,1","+0160,1","99999,9",2000-10-22,01:03:00,35.43333,35.48333,-97.50000,-97.51667,2000-10-22,18:14:00,2000-10-22,18:22:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1364822,72354403954,35.54113,-97.64725,7,"180,5,N,0046,5","+0233,5","22000,5,9,N","016093,5,N,5","+0122,5","10062,5",2021-10-13,21:53:00,35.50800,35.53700,-97.45950,-97.39300,2021-10-13,04:22:00,2021-10-13,04:28:00
1364823,72354403954,35.54113,-97.64725,7,"180,5,N,0041,5","+0222,5","22000,5,9,N","016093,5,N,5","+0122,5","10065,5",2021-10-13,22:53:00,35.47500,35.49200,-97.56200,-97.51000,2021-10-13,04:15:00,2021-10-13,04:19:00
1364824,72354403954,35.54113,-97.64725,7,"180,5,N,0041,5","+0222,5","22000,5,9,N","016093,5,N,5","+0122,5","10065,5",2021-10-13,22:53:00,35.50800,35.53700,-97.45950,-97.39300,2021-10-13,04:22:00,2021-10-13,04:28:00
1364825,72354403954,35.54113,-97.64725,7,"200,5,N,0026,5","+0200,5","22000,5,9,N","016093,5,N,5","+0133,5","10073,5",2021-10-13,23:53:00,35.47500,35.49200,-97.56200,-97.51000,2021-10-13,04:15:00,2021-10-13,04:19:00
1364826,72354403954,35.54113,-97.64725,7,"200,5,N,0026,5","+0200,5","22000,5,9,N","016093,5,N,5","+0133,5","10073,5",2021-10-13,23:53:00,35.50800,35.53700,-97.45950,-97.39300,2021-10-13,04:22:00,2021-10-13,04:28:00

In [142]:
(final_df[final_df['YEAR-MONTH-DAY']!=final_df['BEGIN_DATE']]['BEGIN_DATE']).unique()

array([nan], dtype=object)

In [12]:
data = pd.read_csv("Data/Storm Event Data/Raw Data/2021_storm_events.csv")
data[(data['STATE']== 'OKLAHOMA') & (data['EVENT_TYPE']== 'Tornado')]

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
2707,202111,10,1926,202111,10,1927,163173,989131,OKLAHOMA,40,...,5.0,NNE,BROKEN ARROW,36.1180,-95.7610,36.1200,-95.7550,Strong to severe thunderstorms developed into ...,"This brief tornado damaged barns, snapped larg...",CSV
2709,202111,10,1914,202111,10,1916,163173,989130,OKLAHOMA,40,...,2.0,SW,TULSA,36.1320,-95.9760,36.1320,-95.9670,Strong to severe thunderstorms developed into ...,"This tornado developed over Woodward Park, whe...",CSV
4081,202104,27,2300,202104,27,2310,157751,954167,OKLAHOMA,40,...,5.0,ENE,PAULS VALLEY,34.7000,-97.1720,34.7560,-97.1400,A slow moving trough and a dryline helped init...,A tornado developed about 4 miles southeast of...,CSV
7631,202104,27,1815,202104,27,1815,157751,954166,OKLAHOMA,40,...,9.0,S,HOLLISTER,34.2100,-98.8900,34.2100,-98.8900,A slow moving trough and a dryline helped init...,A storm chaser observed a brief tornado estima...,CSV
12560,202104,28,501,202104,28,504,157141,949925,OKLAHOMA,40,...,4.0,WNW,STILWELL,35.8240,-94.7260,35.8360,-94.7030,Strong to severe thunderstorms moved through e...,This tornado produced a tornadic debris signat...,CSV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60498,202110,12,1838,202110,12,1838,163477,987096,OKLAHOMA,40,...,5.0,SW,FREDERICK,34.3388,-99.0820,34.3388,-99.0820,A warm front lifted north during the afternoon...,"Several storm chasers, including an off-duty m...",CSV
60499,202110,12,2000,202110,12,2007,163477,987103,OKLAHOMA,40,...,5.0,WNW,MEERS,34.7780,-98.6850,34.8030,-98.6610,A warm front lifted north during the afternoon...,Radar indicated strong rotation with a tornado...,CSV
60521,202110,26,2336,202110,26,2345,163479,987380,OKLAHOMA,40,...,2.0,SE,STANLEY DRAPER LAKE DAM,35.2580,-97.4130,35.3110,-97.3250,A dryline and strong upper trough combined to ...,A tornado from a QLCS (quasi-linear convective...,CSV
60525,202110,10,1802,202110,10,1804,163476,986965,OKLAHOMA,40,...,5.0,SSE,LAKE CHICKASHA DAM,35.0550,-98.1120,35.0610,-98.0930,An unseasonably warm and moist airmass was in ...,Storm chasers observed a tornado that develope...,CSV
60535,202110,12,1748,202110,12,1748,163477,987094,OKLAHOMA,40,...,4.0,NNW,RETROP,35.2092,-99.3973,35.2092,-99.3973,A warm front lifted north during the afternoon...,A storm chaser observed a brief tornado near S...,CSV

In [ ]:
# Load in merged data frame 
# copied and pasted from Data/Data Scripts/merge_station_and_event_data_script.py

import pandas as pd
import numpy as np
import os
import math

# What this does: Counts the frequency of non nan's for each feature for each station
# and organizes this information into Features_No_NAN_Counts.csv.

# Note: In the documentation (isd-format-document.pdf) sometimes a number 
# stands in for a nan value. We will deal with that if we choose such a 
# feature later on.


dirc = 'Data/OK City Station Data/Raw Data'
raw_station_data = os.listdir('Data/OK City Station Data/Raw Data') # list files in directory

station_csv_files = [file for file in raw_station_data if ('.csv' in file) and ('Station' in file)] # get csv files

station_list = [] # to hold station numbers as keys and number of csv files as entries

for file in station_csv_files:
    underscore_split = file.split('_')
    station_num = underscore_split[1].replace('.csv','')  
    station_list.append(int(station_num)) # station_num is a string
    


# Read in CSV's as pd.DataFrame's concat along axis = 0 

station_pd_dfs=[pd.read_csv(f"{dirc}/{file}").copy() for file in station_csv_files]
stations_df = pd.concat(station_pd_dfs, axis = 0)
new_df = stations_df.reset_index().drop(['index', 'Unnamed: 0'], axis =1).copy()



new_df['YEAR-MONTH-DAY'] = new_df['DATE'].apply(lambda r: r.split('T')[0])
new_df['TIME'] = new_df['DATE'].apply(lambda r: r.split('T')[1])
new_df.drop(['DATE'],axis=1,inplace=True)

# combined oklahoma tornadoes

### CHANGED CODED
for year in range(2000,2022):
    path = 'Data/Storm Event Data/RAW Data/oklahoma_tornadoes_2000_2021.csv'
    df2 = pd.read_csv(path).copy()


df2 = df2[
        [
        'BEGIN_DATE_TIME', 
        'END_DATE_TIME', 
        'BEGIN_LAT', 
        'END_LAT', 
        'BEGIN_LON', 
        'END_LON'
        ]
        ]

# columns BEGIN-DATE and BEGIN-TIME
new_df2 = df2.copy()
new_df2['BEGIN_DATE'] = df2['BEGIN_DATE_TIME'].apply(lambda r : r.split(' ')[0])
new_df2['BEGIN_TIME'] = df2['BEGIN_DATE_TIME'].apply(lambda r : r.split(' ')[1])
new_df2['END_DATE'] = df2['END_DATE_TIME'].apply(lambda r : r.split(' ')[0])
new_df2['END_TIME'] = df2['END_DATE_TIME'].apply(lambda r : r.split(' ')[1])

new_df2.drop(['BEGIN_DATE_TIME','END_DATE_TIME'],axis=1,inplace=True)

# Change format of 'BEGIN_DATE' and 'END_DATE' to match that of 'YEAR_MONTH_DAY' in station data

month_num = {
            'JAN':'01',
            'FEB':'02',
            'MAR':'03', 
            'APR':'04', 
            'MAY':'05', 
            'JUN':'06', 
            'JUL':'07', 
            'AUG':'08', 
            'SEP':'09', 
            'OCT':'10', 
            'NOV':'11', 
            'DEC':'12'
            }

new_df2['BEGIN_DATE'] = new_df2['BEGIN_DATE'].apply(lambda r: f'{r.split('-')[0]}-{month_num[r.split('-')[1]]}-{r.split('-')[2]}')
new_df2['END_DATE'] = new_df2['END_DATE'].apply(lambda r: f'{r.split('-')[0]}-{month_num[r.split('-')[1]]}-{r.split('-')[2]}')

# Get year to be 20**
new_df2['BEGIN_DATE']=new_df2['BEGIN_DATE'].apply(lambda r: f'20{r.split('-')[2]}-{r.split('-')[1]}-{r.split('-')[0]}')
new_df2['END_DATE']=new_df2['END_DATE'].apply(lambda r: f'20{r.split('-')[2]}-{r.split('-')[1]}-{r.split('-')[0]}')

data = pd.merge(left=new_df,right=new_df2,how ='outer',left_on='YEAR-MONTH-DAY',right_on='BEGIN_DATE')

In [3]:
#cleaning storm data

import pandas as pd

df_collect = []

for year in range(2000, 2022):
    print(f"Processing {year}...")
    
    # Load each years CSV
    df = pd.read_csv(f'Data/Storm Event Data/Raw Data/{year}_storm_events.csv')
    
    # Filter for Oklahoma tornado events
    df_ok_tornado = df[
        (df['STATE'] == 'OKLAHOMA') &
        # Don't use this (df['CZ_NAME'] == 'OKLAHOMA') &
        (df['EVENT_TYPE'] == 'Tornado')
    ]
    
    df_collect.append(df_ok_tornado)
    
    # Save filtered data for that year
    df_ok_tornado.to_csv(f'Data/Storm Event Data/Cleaned Data/NEW_{year}_oklahoma_tornadoes.csv', index=False)
    
    print(f"Saved {len(df_ok_tornado)} rows for {year}.")

Processing 2000...
Saved 46 rows for 2000.
Processing 2001...
Saved 70 rows for 2001.
Processing 2002...
Saved 23 rows for 2002.
Processing 2003...
Saved 88 rows for 2003.
Processing 2004...
Saved 65 rows for 2004.
Processing 2005...
Saved 28 rows for 2005.
Processing 2006...

/var/folders/_y/61ngw3jd5739nsvht6fg3wfr0000gn/T/ipykernel_22993/2069012300.py:11: DtypeWarning: Columns (29,34,35,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'Data/Storm Event Data/Raw Data/{year}_storm_events.csv')

Saved 28 rows for 2006.
Processing 2007...
Saved 58 rows for 2007.
Processing 2008...
Saved 85 rows for 2008.
Processing 2009...
Saved 39 rows for 2009.
Processing 2010...
Saved 123 rows for 2010.
Processing 2011...
Saved 143 rows for 2011.
Processing 2012...
Saved 71 rows for 2012.
Processing 2013...
Saved 96 rows for 2013.
Processing 2014...
Saved 16 rows for 2014.
Processing 2015...
Saved 129 rows for 2015.
Processing 2016...
Saved 71 rows for 2016.
Processing 2017...
Saved 97 rows for 2017.
Processing 2018...
Saved 54 rows for 2018.
Processing 2019...
Saved 172 rows for 2019.
Processing 2020...
Saved 41 rows for 2020.
Processing 2021...
Saved 68 rows for 2021.

In [4]:
combined_df = pd.concat(df_collect,axis =0)
combined_df.to_csv('Data/Storm Event Data/Cleaned Data/NEW_Oklahoma_Tornadoes_2000_2021.csv')